### ISSUE TITLE
Not working with Cassandra 3.11

### ISSUE THREAD

**Issue by deniszh** [instaclustr/cassandra-sstable-tools#6]
```
+ ant -Dcassandra.version=3.11.2
Buildfile: /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/build.xml

clean:

cassandra-check:

download:
    [mkdir] Created dir: /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/cassandra/downloads
      [get] Getting: http://archive.apache.org/dist/cassandra/3.11.2/apache-cassandra-3.11.2-bin.tar.gz
      [get] To: /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/cassandra/downloads/apache-cassandra-3.11.2-bin.tar.gz

extract:
    [mkdir] Created dir: /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/cassandra/3.11.2
    [untar] Expanding: /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/cassandra/downloads/apache-cassandra-3.11.2-bin.tar.gz into /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/cassandra
     [move] Moving 5635 files to /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/cassandra

compile:
    [mkdir] Created dir: /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/build/classes
     [copy] Copying 5 files to /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/src
    [javac] Compiling 23 source files to /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/build/classes
    [javac] /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/src/com/instaclustr/sstabletools/cassandra/PurgeStatisticBackend.java:224: error: method purge in interface Row cannot be applied to given types;
    [javac]             return row.purge(purger, nowInSec);
    [javac]                       ^
    [javac]   required: DeletionPurger,int,boolean
    [javac]   found: DeletionPurger,int
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/src/com/instaclustr/sstabletools/cassandra/PurgeStatisticBackend.java:228: error: method purge in interface Row cannot be applied to given types;
    [javac]             return row.purge(purger, nowInSec);
    [javac]                       ^
    [javac]   required: DeletionPurger,int,boolean
    [javac]   found: DeletionPurger,int
    [javac]   reason: actual and formal argument lists differ in length
    [javac] Note: /var/lib/jenkins/jobs/cassandra-sstable-tools/workspace/src/com/instaclustr/sstabletools/cassandra/CassandraBackend.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors
```

**Comment by grom358** [comment]
This is fixed now. The Cassandra interfaces changes every now and then. I have changed to uses branches instead of the `-Dcassandra.version` flag. Checkout cassandra-3.11 branch and change build.xml to use 3.11.2 and it will build.

`Camerons-MacBook-Pro:cassandra-sstable-tools $ ant
Buildfile: /Users/grom/dev/cassandra-sstable-tools/build.xml

clean:
   [delete] Deleting directory /Users/grom/dev/cassandra-sstable-tools/build

cassandra-check:

download:
      [get] Getting: http://archive.apache.org/dist/cassandra/3.11.2/apache-cassandra-3.11.2-bin.tar.gz
      [get] To: /Users/grom/dev/cassandra-sstable-tools/cassandra/downloads/apache-cassandra-3.11.2-bin.tar.gz

extract:
    [mkdir] Created dir: /Users/grom/dev/cassandra-sstable-tools/cassandra/3.11.2
    [untar] Expanding: /Users/grom/dev/cassandra-sstable-tools/cassandra/downloads/apache-cassandra-3.11.2-bin.tar.gz into /Users/grom/dev/cassandra-sstable-tools/cassandra
     [move] Moving 5635 files to /Users/grom/dev/cassandra-sstable-tools/cassandra

compile:
    [mkdir] Created dir: /Users/grom/dev/cassandra-sstable-tools/build/classes
    [javac] Compiling 23 source files to /Users/grom/dev/cassandra-sstable-tools/build/classes
    [javac] Note: /Users/grom/dev/cassandra-sstable-tools/src/com/instaclustr/sstabletools/cassandra/CassandraBackend.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

jar:
    [mkdir] Created dir: /Users/grom/dev/cassandra-sstable-tools/dist/3.11.2
      [jar] Building jar: /Users/grom/dev/cassandra-sstable-tools/dist/3.11.2/ic-sstable-tools.jar

BUILD SUCCESSFUL
Total time: 1 minute 16 seconds`
